{% set name = "slda" %}
{% set version = "0.1.6" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/Savvysherpa/slda/archive/{{ version }}.tar.gz
    sha256: aeabfe4edefc566ee97c107f8f9b2c6a478595e24fb35d44d9eeaaa876fb90ce

build:
    number: 3
    skip: True  # [win or not py3k]

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - cython
        - cythongsl
        - gsl
        - numpy
        - python
        - setuptools

    run:
        - cython
        - cythongsl
        - gsl
        - {{ pin_compatible('numpy') }}
        - pypolyagamma
        - python
        - scikit-learn
        - scipy

test:
    imports:
        - slda

about:
    home: https://github.com/Savvysherpa/slda
    license: MIT
    summary: >
      Cython implementations of Gibbs sampling for latent
      Dirichlet allocation and its supervised variants
      
extras:
    maintainers:
      - Savvysherpa
