travis:
  secure:
    BINSTAR_TOKEN: WqA/sY6DODrxa0VK41zh2656Vo6Jr7yctOKZ1fzAYDkiFYGr7Q4t63ijJc6e9EWWd0kn3ItxQPqiX9jNB5cy1s5BROBM3iNcAR6DdAsiXhA1Zj2hBHUOtUy8sVjkaZzDvCdmtcRszbPfs4xTGhIbhSTmfpxWZsk9osOfgFwThYWve4Zlc1Gb4YBeqyGKYKmNwkD/KS1d3el13FtFz8H6ZUHAC6fsevUNBuYkFznsU2RULtLeiPTn5F5rfJehoSFuboW4rHE/mc4g+tKjOH/IsHkiCAOj+JRfemD8VzcgvxghGvCvSj8Gsj12eStcj3QQMURNxVdg+s5ZdpNXDT6Qv63s7Wf3kT8fQiYnOHp+O8aavuqZNeuLx5blXzNZUetOV1ZJTHVhUrs7xXfXI0kFi4joQDF8GUECobyyvftOivGCfkreBUCGXg7/ahh+SK/xo70j00dKjRxH8J7VBiNf2nShcza1OZ8i3EgqsupNETBGoAUQ3OLyARfEWP9+JkkJEYTg9iZqAnyKuG80LJBF1RQDuYnRb4YPqGWiS2ZOdI11iI774Ie46X13y2EmTNEjFi8jUet6+77ug/74qpQPBkaIgLECqiWSnlFEaM2CVXPPaJpALsIkljfxYW+CL8B6B8rGAj+2BPItCFz3NwWgQR4SH/ltRuFAgKPJiHKDu28=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
