appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: yR55r6v3HemLpneOeRNruEOTZMaxIp8xDDjsSnfFLHJNHMRXqh8fkyIqX+7kwEAJih60QY0SUxQtU22QTS4oHTHCduWa/CtzY+phaaRdzzGcTnUKo0HmEbSPkeIGTQMw73bnElT6MJFL5LLVi64W/Jbt4+3qiBEOh1p5/YWHTUIaiGoMlCL1cPxh6+6OkGhAcTh502dM8Fpjd3sunquY2nJZwnvV6/EW7iBFHMwl4nGEG7izztxGB1O1qCZUXaHn7hT0r7qDW1KCHifjShel0UlgOLCo2qmtCSsyu50KZTVVENUJ9em7ItQoju9uJxc2vHlhxy6OglrrI1pzu2/k8O6VJrcH+G8nqyppxpm2qe2hsEJAPkHLYM4YM9k61FLz1Uaw5/LhocK0wSKNLc9gVx1TvnGpT6sYlz/yHtvDc9rFzPm0fIImy2Dv5OxYHuY1dV2bdiWh9S7zBYryNMQj5o9WlDH9ZGmBDYlJdPeCwWzLSNxul9X7jeHEoXyz7hCjIj6eEFdPsqRqrM+2saY5f9iWIBSzlSxhettCGoJ8+3oqB1B1QNqkdCVGb0UD+GNLhaRpNe8swwLwCc1tpdnK4SuTbKNNx+kOvqbQn3ElmSingJQ1qF7G0vEOGEz1DB2PUpNRvFRiVPlczH1lCgVYITFFIjuY5d9pJ/MuEv2q6jE=}
